export const POSITIVE_KEYWORDS = [
  "happy",
  "excited",
  "joy",
  "love",
  "help",
  "support",
  "achieve",
  "success",
  "positive",
  "good",
  "great",
  "wonderful",
  "amazing",
  "fantastic",
  "calm",
  "peaceful",
  "relaxed",
  "confident",
  "proud",
  "grateful",
  "blessed",
  "yes",
  "agree",
  "like",
  "enjoy",
  "fun",
  "nice",
  "better",
  "improve",
  "learn",
];

export const NEGATIVE_KEYWORDS = [
  "sad",
  "angry",
  "frustrated",
  "worried",
  "anxious",
  "stress",
  "conflict",
  "negative",
  "bad",
  "terrible",
  "awful",
  "hate",
  "fear",
  "scared",
  "lonely",
  "depressed",
  "hopeless",
  "angry",
  "irritated",
  "annoyed",
  "no",
  "disagree",
  "hate",
  "dislike",
  "boring",
  "difficult",
  "hard",
  "problem",
  "issue",
];

export const EMOTIONAL_NEEDS_KEYWORDS = {
  support: ["support", "help", "care"],
  connection: ["connection", "social", "people"],
  space: ["space", "alone", "quiet"],
  understanding: ["understanding", "listen", "empathy"],
  recognition: ["recognition", "appreciate", "acknowledge"],
};

export const PERSONALITY_IMPACT_KEYWORDS = {
  "emotional intelligence": {
    agreeableness: ["talk", "communicate", "discuss"],
    openness: ["meditate", "reflect", "think"],
    neuroticism: ["exercise", "activity"],
  },
  personality: {
    agreeableness: ["social", "group", "people"],
    neuroticism: ["alone", "quiet", "solitude"],
    openness: ["creative", "art", "music"],
  },
  relationships: {
    agreeableness: ["help", "support", "care"],
    neuroticism: ["confront", "argue", "fight"],
    openness: ["listen", "understand"],
  },
  "self-awareness": {
    agreeableness: [],
    openness: ["reflect", "think", "analyze"],
    neuroticism: ["journal", "write"],
  },
  "stress management": {
    openness: [],
    neuroticism: ["breathe", "relax", "calm"],
    agreeableness: ["avoid", "ignore"],
  },
};
